FROM ruby:latest
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | \
    apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | \
    tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -qq -y build-essential \
    nodejs \
    yarn \
    postgresql-client \
    libpq-dev

WORKDIR '/app'

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock


COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

RUN bundle install
RUN yarn install

# CMD ["rails", "server", "-b", "0.0.0.0"]
